name: CI - Json Validation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20'  # Specify your Node.js version
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Deps
        run: pnpm install

      - name: Run Tests
        run: pnpm test